insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "组织工作实行党中央集中统—领导，各级党委（党组）分级分类领导，组织部门专门负责，有关方面各司其职、密切配合的领导体制。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "中央组织部领导各级组织部门工作，上级组织部门指导下级组织部门工作。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "中央组织部和地方党委组织部的主要职责有：负责公务员工作的统—管理；负责离退休干部工作的统—管理；统—管理机构编制委员会办公室。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "建立健全组织部门、统战部门协作配合机制。在动议和讨论决定党外干部的任免、调动、交流前，应当征求统战部门的意见。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "加强对党外代表人士的管理，重点了解掌握其日常表现、思想状况、履行职责、廉洁自律和个人重要事项变化情况，特别是在重大原则问题上的政治立场和态度。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "各级党委应当把党外代表人士队伍建设纳入干部和人才队伍建设总体规划，在优秀年轻干部队伍中统筹考虑党外干部。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "党员有党内监督权，有权在党的会议上以口头或者书面方式有根据地批评党的任何组织和任何党员，揭露、要求纠正工作中存在的缺点和问题，在民 主评议中指出领导干部和其他党员的缺点错误；有权 向党组织反映对本人所在党组织、领导干部、其他党 员的意见。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "党组织讨论决定问题必须坚持民主集中制，执行少数服从多数原则，决定重要问题应当按照规定进行无记名投票表决。表决前应当充分讨论酝酿，表决情况和不同意见及其理由应当如实记录。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "党员被依法留置、逮捕的，党组织应当按照管理权限中止其表决权、选举权和被选举权等党员权利。根据监察机关、司法机关处理结果，可以恢复其党员权利的， 应当及时予以恢复。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "党委应当坚持党建工作与重点工作同谋划、同部署、同推进、同考核，加强对本单位本系统全面从严治党各项工作的领导。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "党的建设工作领导小组是党委抓全面从严治党的议事协调机构。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "机关党委在上级党委或者党的机关工作委员会和本单位党委领导下，协助本单位负责人完成任务，改进工作，对包括本单位负责人在内的每个党员进行教音、管理、监督，领导本单位业务工作。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "党建工作部门要加强党内监督，发挥职能监督作用。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "党支部党员大会—般每季度召开1次，党支部委员会会议—般每月召开1次，党小组会—般每月召开1次。党支部每月相对固定1天开展主题党日，每年至少召开1次组织生活会，—般每年开展1次民主评议党员。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "全民守法是法治社会的基础工程。树立宪法法律至上、法律面前人人平等的法治理念。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "法治社会是构筑法治国家的基础，法治社会建设是实现国家治理体系和治理能力现代化的重要组成部分。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "深入学习宣传习近平法治思想，深入宣传以法律为核心的中国特色社会主义法律体系，广泛宣传与经济社会发展和人民群众利益密切相关的法律法规，使	人民群众自觉尊崇、信仰和遵守法律。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "在全国代表大会闭会期间，中央委员会领导党的全部工作，对外代表中国共产党。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "中央委员会委员和候补委员必须有三年以上的党龄。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "党的十九届五中全会强调，要坚持扩大内需这个战略基点，加快培育完整内需体系，把实施扩大内需战略同深化供给侧结构性改革有机结合起来，以创新驱动、高质量供给引领和创造新需求。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "党的十九届五中全会提出，形成强大国内市场，构建新发展格局。坚持扩大内需这个战略基点， 加快培育完整内需体系，把实施扩大内需战略同深化 供给侧结构性改革有机结合起来，以创新驱动、高质 量供给引领和创造新需求。要畅通国内大循环，促进国内国际双循环，全面促进消费，拓展投资空间。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "党的十九届五中全会提出，繁荣发展文化事业和文化产业，提高国家文化软实力。坚持马克思主义在意识形态领域的指导地位，坚定文化自信，坚持以马克思主义理论引领文化建设，加强社会主义精神文明建设，围	绕举旗帜、聚民心、育新人、兴文化、展形象的使命任务，促进满足人民文化需求和增强人民精神力量相统—，推进社会主义文化强国建设。要提高社会文明程度，提升公共文化服务水平，健全现代文化产业体系。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "党的十九届五中全会提出，推动绿色发展，促进人与自然和谐共生。坚持绿水青山就是金山银山理念，坚持尊重自然、顺应自然、保护自然，坚持节 约优先、保护优先、自然恢复为主，守住自然生态安 全边界。深入实施科学发展战略， 完善生态文明领域统筹协调机制，构建生态文明体系，促进经济社会发 展全面绿色转型，建设人与自然和谐共生的现代化。 要加快推动绿色低碳发展，持续改善环境质量，提升 生态系统质量和稳定性， 全面提高资源利用效率。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "党的十九届五中全会提出，改善人民生活品质，提高社会建设水平。坚持把实现好、维护好、发展好最广大人民根本利益作为发展的出发点和落脚点，尽力而为、量力而行，健全基本公共服务体系，完善共建共治共享的社会治理制度，扎实推动共同富  裕，不断增强人民群众获得感、幸福感、安全感，促进人的全面发展和社会全面进步。要提高人民收入水平，强化就业优先政策，建设高质量教育体系，健全多层次社会保障体系，全面推进健康中国建设，实施积极应对人口老龄化国家战略，加强和创新社会治理。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "我们所要坚守的政治方向，就是共产主义远大理想和中国特色社会主义共同理想、“两个—百年”奋斗目标，就是党的基本理论、基本路线、基本方略。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "带头做到“两个维护”，从根本上讲就是要做到对党忠诚。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "前进征程上，我们要坚持中国共产党领导，坚持人民主体地位，坚持中国特色社会主义道路，全面贯彻执行党的基本理论、基本路线、基本方略，不断满足人民对美好生活的向往，不断创造新的历史伟业。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "领导干部要胸怀两个大局，—个是中华民族伟大复兴的战略全局，—是世界百年未有之大变局，是我们谋划工作的基本出发点。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "要继续坚持内紧外松的要求，绷紧疫情防控这根弦，完善常态化防控机制，确保疫情不出现反弹。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "公有制为主体、多种所有制经济共同发展，按劳分配为主体、多种分配方式并存，社会主义市场经济体制等社会主义基本经济制度，既有利于激发各类市场主体活力、解放和发展社会生产力，又有利于促进效率和公平有机统—、不断实现共同富裕。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "我国经济潜力足、人口多、回旋空间大、政策工具多的基本特点没有变。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "我国具有全球最完整、规模最大的工业体系、强大的生产能力、完善的配套能力， 拥有1亿多市场主体和1.7亿多受过高等教育或拥有各类专业技能的人才，还有包括4亿多中等收入群体在内的14亿人口所形成的超大规模内需市场，正处千新型工业化、信息化、城镇化、农业现代化快速发展阶段，投资需求潜力巨大。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "习近平强调，做好“六稳“工作、落实“六保“任务至关重要。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "政务处分决定自下发文件之日起生效。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "记过处分的期间是十个月。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "大兴调查研究之风，把调查研究贯穿工作谋划、决策和执行全过程，贯穿发现和解决问题、密切党群干群关系全过程。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "开展专项巡察是解决工作中突出问题的有效方法和重要抓手。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "坚持党的领导是社会主义法治的根本要求，是全面依法治国题中应有之义。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "党是最高政治领导力量，党的领导是我们的最大制度优势。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "中国特色社会主义制度是中国特色社会主义最本质的特征，中国共产党是国家最高政治领导力量，是实现中华民族伟大复兴的根本保证。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "坚持党的领导，首先是坚持党中央权威和集中统—领导，这是党的领导的最高原则。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "改革开放40年的时间启示我们：中国共产党领导是中国特色社会主义最本质的特征，是中国特色社会主义制度的最大优势。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 基层党组织是贯彻落实党中央决策部署的“最后一公里”，要坚持大抓基层的鲜明导向，抓紧补齐基层党组织领导基层治理的各种短板。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 要教育引导全党自觉在思想上政治上行动上同党中央保持高度一致，保持坚强政治定力和正确前进方向，充分发挥各级党委（党组）、各领域基层党组织的政治功能和组织功能。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 上届党的委员会成立代表资格审查小组，负责对代表的产生程序和资格进行审查。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 委员会选举的监票人，从是书记、副书记、常务委员会委员候选人的委员中推选，经全体委员表决通过。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 选举人不能填写选票的，不可以由本人委托非候选人按照选举人的意志代写。因故未出席会议的党员或者代表不能委托他人代为投票。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 落实全面从严治党责任，严禁拉帮结派、拉票贿选、跑风漏气等非组织行为，严防黑恶势力、宗族势力、宗教势力干扰破坏选举，强化监督检查和责任追究，确保选举工作风清气正。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 获得赞成票超过半数的被选举人数少于应选名额时，对不足的名额另行选举。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 要把提高管理水平作为新时代干部队伍建设的重大任务，通过加强思想淬炼、政治历练、实践锻炼、专业训练，推动广大干部严格按照制度履行职责、行使权力、开展工作。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 基层党组织是贯彻落实党中央决策部署的“最后一公里”，要坚持大抓基层的鲜明导向，抓紧补齐基层党组织领导基层治理的各种短板，把各领域基层党组织建设成为实现党的领导的坚强战斗堡垒，充分发挥广大党员在改革发展稳定中的先锋模范作用。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 党的十九届四中全会把健全维护党的集中统一的组织制度作为坚持和完善党的领导制度体系的重要内容，纳入国家制度和国家治理体系之中。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 要深化干部制度改革，完善管思想、管工作、管作风、管纪律的从严管理机制，推动形成能者上、优者奖、庸者下、劣者汰的正确导向。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 要加强马克思主义特别是新时代中国特色社会主义思想的理论武装，使各级党组织和广大党员、干部特别是领导干部掌握马克思主义理论武器，提高马克思主义理论水平和运用能力，共同把党的创新理论转化为推进新时代中国特色社会主义伟大事业的实践力量。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 政府工作报告：2020年，大型商业银行普惠型小微企业贷款增速要高于40%。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 政府工作报告：2019年，大众创业万众创新深入开展，企业数量日均净增2万户以上。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 政府工作报告：推动煤炭清洁高效利用，发展可再生能源，完善石油、天然气、电力产供销体系，提升能源储备能力。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 政府工作报告：今年居民医保人均财政补助标准增加30元，开展门诊费用跨省直接结算试点。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 政府工作报告：今年，加强交通、水利等重大工程建设。增加国家铁路建设资本金1000亿元。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 2019年10月，党的十九届中央委员会第四次全体会议，审议通过了《中共中央关于坚持和完善中国特色社会主义制度、推进国家治理体系和治理能力现代化若干重大问题的决定》。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 习近平指出，要统筹应急状态下医疗卫生机构动员响应。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 中国共产党在领导社会主义事业中，必须坚持以政治建设为中心，其他各项工作都服从和服务于这个中心。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 中国梦的核心是实现中华民族的伟大复兴，基本内涵是实现国家富强、民族振兴、人民幸福。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 党的政治建设是党的根本性建设，决定党的建设方向和效果。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 党内民主是党的生命，是党内政治生活积极健康的重要基础。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 中国共产党领导是中国特色社会主义最本质的特征，是中国特色社会主义制度的最大优势。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 党员受到开除党籍处分，终生不得重新入党。另有规定不准重新入党的，依照规定。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 发展党员，必须把工作表现放在首位，经过党的支部，坚持个别吸收的原则。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 2019年4月20日，由中国国家税务总局主办的第一届“一带一路”税收征管合作论坛是现代多边税收合作机制和国际税收体系的有益补充，有利于促进实现联合国2030年可持续发展目标。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 中国特色社会主义是改革开放以来党的全部理论和实践的主题。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 中国梦的基本内涵是国家富强、民族振兴、人民幸福。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 我国正处于并将长期处于社会主义初级阶段。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 由于国内的因素和国际的影响，阶级斗争还在一定范围内长期存在。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 党组织和党员违反党章和其他党内法规，违反国家法律法规，违反党和国家政策，违反共产主义道德，危害党、国家和人民利益的行为，依照规定应当给予纪律处理或者处分的，都必须受到追究。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 十九大报告提出一个新目标，即“在本世纪中叶建成富强民主文明和谐的社会主义现代化强国”。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 从2020年到2035年,在全面建成小康社会的基础上,再奋斗十五年,全面实现社会主义现代化。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 党的组织建设是党的根本性建设，决定党的建设方向和效果。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 带头做到“两个维护”，是加强中央和国家机关党的建设的首要任务。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 新时代我国社会主要矛盾是人民日益增长的美好生活需要和不平衡不充分的发展之间的矛盾，必须坚持以科学发展为中心的发展思想，不断促进人的全面发展、全体人民共同富裕。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 全面从严治党是中国共产党的自我革命，目标是保持党同人民群众的血肉联系，始终保持党的先进性和纯洁性。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 中国特色社会主义最本质的特征是人民当家作主。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 统筹推进疫情防控和经济社会发展，要变压力为动力、善于化危为机。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 思想建设是党的基础性建设。要把坚守共产党人精神追求作为党的思想建设的首要任务。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 政治方向是党生存发展第一位的问题，事关党的前途命运和事业兴衰成败。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 中央和国家机关是践行“两个维护”的第一方阵，必须牢固树立政治机关的意识。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 习近平总书记在中共十八届中央纪委七次全会上讲话时指出，增强政治意识、大局意识、核心意识、看齐意识，最终要落脚在看齐上。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 全面从严治党，核心是加强党的领导，基础在全面，关键在严，要害在治。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 党支部召开党员大会，按照个人自评、党员互评、领导点评的程序，组织党员进行评议。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 党支部应当经常开展谈心谈话。党支部委员之间、党支部委员和党员之间、党员和党员之间，每年谈心谈话一般不少于1次。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 “稳”和“进”是辩证统一的关系，“进”是主基调，要在保持大局稳定的前提下谋进。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 加强中央和国家机关党的建设的首要任务是带头做到“两个维护”。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 中国特色社会主义有很多特点和特征，但最本质的特征是坚持以人民为中心。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 目前，我国具有全球最完整、规模最大的工业体系、强大的生产能力和完善的配套能力。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 依法治国首先要坚持依宪治国，依法执政首先要坚持依宪执政。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 中国共产党领导的多党合作和政治协商制度是中国特色社会主义制度的重要制度。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 推动税务系统全面从严治党，要坚持不懈压牢压实各级税务局党委和班子成员特别是“纪检组长”管党治党责任。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 党的十九届四中全会通过的《决定》指出，我国国家制度和国家治理体系具有多方面的显著优势，其中之一是：坚持以才为主、选贤任能，聚天下英才而用之，培养造就更多更优秀人才的显著优势。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 加快建立现代财政制度是完善和发展中国特色社会主义制度、推进国家治理体系和治理能力现代化的题中应有之义。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 完善坚持正确导向的舆论引导工作机制，应坚持党管媒体原则，建立以新媒体建设为根本、先进技术为支撑、创新管理为保障的全媒体传播体系。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 2020年3月4日，习近平总书记主持召开中共中央政治局常务委员会会议指出，要突出抓好北京等重点地区疫情防控，完善京津冀联防联控机制，在人员流动引导、交通通道防疫、企业复工复产等方面加强协调联动。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 党的十九届四中全会明确提出：“深入推进简政放权、放管结合、优化服务，深化行政审批制度改革，改善营商环境，激发政府活力。” （ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 制度的生命力在于执行，健全权威高效的制度执行机制，加强对制度执行的监督，应坚决杜绝做选择、搞变通、打折扣的现象。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 我国是工人阶级领导的、以工农联盟为基础的人民民主专政的社会主义国家，国家的一切权力属于党。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 坚持全国武装力量由军委主席统一领导和指挥，完善贯彻军委主席负责制的体制机制，严格落实军委主席负责制各项制度规定。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 坚持按劳分配为主体、多种分配方式并存，应坚持多劳多得，着重保护劳动所得，增加劳动者特别是一线劳动者劳动报酬，提高资本要素在初次分配中的比重。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 要实现各种所有制经济的权利平等、机会平等、发展平等。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 坚持奉行防御性的国防政策，永远不称霸，永远不搞扩张，永远做维护世界和平的坚定力量。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 《中国共产党第十九届中央委员会第四次全体会议公报》提出，适当加强中央在知识产权保护、养老保险、跨区域生态环境保护等方面事权，减少并规范中央和地方共同事权。赋予地方更多自主权，支持地方创造性开展工作。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 维护党中央权威和集中统一领导，首先要维护习近平总书记的核心地位。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 2020年2月21日，中共中央政治局常务委员会召开会议，分析新冠肺炎疫情形势，研究加强防控工作，会议指出，要积极扩大外需、稳定内需。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 “一国两制”是党领导人民实现祖国和平统一的一项重要制度，是中国人民的一个伟大创举。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 2020年政府工作报告指出，要深入推进新型城镇化，发挥特大城市的综合示范作用，培育产业、增加就业。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 2020年4月17日，中共中央政治局召开会议指出，要以更大的宏观政策力度对冲新冠肺炎疫情造成的影响，采取的货币政策要更加灵活适度。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 必须坚定不移地走中国特色社会主义法治道路，需要坚持法治国家、法治政府、法治体系一体建设。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 推进国家治理体系和治理能力现代化，必须发挥税收在国家治理中的基础性、支柱性、战略性作用。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 2020年3月30日，税务总局王军局长在全国税务系统全面从严治党工作会议上，做了《扛牢政治责任 补齐短板弱项--驰而不息推动税务系统全面从严治党向高质量发展》的报告。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 重大经济体制改革的进度决定着其他方面许多体制改革的进度，具有牵一发而动全身的作用。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 坚持社会主义基本经济制度，应充分发挥政府在资源配置中的决定性作用，更好发挥政府作用，全面贯彻新发展理念，坚持以供给侧结构性改革为主线，加快建设现代化经济体系。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 加强公共卫生体系建设，要加强传染病防治能力建设，完善传染病直报和预警系统。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 党的十九届四中全会通过的《决定》指出，坚定不移推进反腐败斗争，坚决查处政治问题和经济问题交织的腐败案件，坚决斩断“围猎”和甘于被“围猎”的利益链，坚决破除权钱交易的关系网。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 坚持和完善党和国家监督体系，强化对权力运行的制约和监督。完善权力配置和运行制约机制。坚持权责法定，健全分事行权、分岗设权、法定授权、分期轮岗制度，明晰权力边界，规范工作流程，强化权力制约。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 加快落实区域发展战略，要深入推进京津冀协同发展、粤港澳大湾区建设、长三角一体化发展。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 目前，我国具有全球最完整、规模最大的工业体系、强大的生产能力和完善的配套能力。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 依法治国首先要坚持依宪治国，依法执政首先要坚持依宪执政。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 中国共产党领导的多党合作和政治协商制度是中国特色社会主义制度的重要制度。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 推动税务系统全面从严治党，要坚持不懈压牢压实各级税务局党委和班子成员特别是“纪检组长”管党治党责任。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 党的十九届四中全会通过的《决定》指出，我国国家制度和国家治理体系具有多方面的显著优势，其中之一是：坚持以才为主、选贤任能，聚天下英才而用之，培养造就更多更优秀人才的显著优势。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 加快建立现代财政制度是完善和发展中国特色社会主义制度、推进国家治理体系和治理能力现代化的题中应有之义。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 完善坚持正确导向的舆论引导工作机制，应坚持党管媒体原则，建立以新媒体建设为根本、先进技术为支撑、创新管理为保障的全媒体传播体系。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 2020年3月4日，习近平总书记主持召开中共中央政治局常务委员会会议指出，要突出抓好北京等重点地区疫情防控，完善京津冀联防联控机制，在人员流动引导、交通通道防疫、企业复工复产等方面加强协调联动。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 党的十九届四中全会明确提出：“深入推进简政放权、放管结合、优化服务，深化行政审批制度改革，改善营商环境，激发政府活力。” （ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 制度的生命力在于执行，健全权威高效的制度执行机制，加强对制度执行的监督，应坚决杜绝做选择、搞变通、打折扣的现象。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 我国是工人阶级领导的、以工农联盟为基础的人民民主专政的社会主义国家，国家的一切权力属于党。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 坚持全国武装力量由军委主席统一领导和指挥，完善贯彻军委主席负责制的体制机制，严格落实军委主席负责制各项制度规定。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 坚持按劳分配为主体、多种分配方式并存，应坚持多劳多得，着重保护劳动所得，增加劳动者特别是一线劳动者劳动报酬，提高资本要素在初次分配中的比重。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 要实现各种所有制经济的权利平等、机会平等、发展平等。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 坚持奉行防御性的国防政策，永远不称霸，永远不搞扩张，永远做维护世界和平的坚定力量。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 《中国共产党第十九届中央委员会第四次全体会议公报》提出，适当加强中央在知识产权保护、养老保险、跨区域生态环境保护等方面事权，减少并规范中央和地方共同事权。赋予地方更多自主权，支持地方创造性开展工作。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 维护党中央权威和集中统一领导，首先要维护习近平总书记的核心地位。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 2020年2月21日，中共中央政治局常务委员会召开会议，分析新冠肺炎疫情形势，研究加强防控工作，会议指出，要积极扩大外需、稳定内需。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 “一国两制”是党领导人民实现祖国和平统一的一项重要制度，是中国人民的一个伟大创举。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 2020年政府工作报告指出，要深入推进新型城镇化，发挥特大城市的综合示范作用，培育产业、增加就业。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 2020年4月17日，中共中央政治局召开会议指出，要以更大的宏观政策力度对冲新冠肺炎疫情造成的影响，采取的货币政策要更加灵活适度。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 必须坚定不移地走中国特色社会主义法治道路，需要坚持法治国家、法治政府、法治体系一体建设。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 推进国家治理体系和治理能力现代化，必须发挥税收在国家治理中的基础性、支柱性、战略性作用。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 2020年3月30日，税务总局王军局长在全国税务系统全面从严治党工作会议上，做了《扛牢政治责任 补齐短板弱项--驰而不息推动税务系统全面从严治党向高质量发展》的报告。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 重大经济体制改革的进度决定着其他方面许多体制改革的进度，具有牵一发而动全身的作用。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 坚持社会主义基本经济制度，应充分发挥政府在资源配置中的决定性作用，更好发挥政府作用，全面贯彻新发展理念，坚持以供给侧结构性改革为主线，加快建设现代化经济体系。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 加强公共卫生体系建设，要加强传染病防治能力建设，完善传染病直报和预警系统。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 党的十九届四中全会通过的《决定》指出，坚定不移推进反腐败斗争，坚决查处政治问题和经济问题交织的腐败案件，坚决斩断“围猎”和甘于被“围猎”的利益链，坚决破除权钱交易的关系网。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 坚持和完善党和国家监督体系，强化对权力运行的制约和监督。完善权力配置和运行制约机制。坚持权责法定，健全分事行权、分岗设权、法定授权、分期轮岗制度，明晰权力边界，规范工作流程，强化权力制约。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 加快落实区域发展战略，要深入推进京津冀协同发展、粤港澳大湾区建设、长三角一体化发展。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "中国共产党领导是中国特色社会主义最本质的特征，是中国特色社会主义制度的最大优势，党是最高政治领导力量。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "坚持全国一盘棋，调动各方面积极性，集中力量办大事是中国特色社会主义制度的显著优势。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "73中国共产党领导的多党合作和政治协商制度是中国特色社会主义制度的重要制度。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 坚持奉行防御性的国防政策，永远不称霸，永远不搞扩张，永远做维护世界和平的坚定力量。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 《中国共产党第十九届中央委员会第四次全体会议公报》提出，适当加强中央在知识产权保护、养老保险、跨区域生态环境保护等方面事权，减少并规范中央和地方共同事权。赋予地方更多自主权，支持地方创造性开展工作。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 维护党中央权威和集中统一领导，首先要维护习近平总书记的核心地位。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 2020年2月21日，中共中央政治局常务委员会召开会议，分析新冠肺炎疫情形势，研究加强防控工作，会议指出，要积极扩大外需、稳定内需。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 “一国两制”是党领导人民实现祖国和平统一的一项重要制度，是中国人民的一个伟大创举。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 2020年政府工作报告指出，要深入推进新型城镇化，发挥特大城市的综合示范作用，培育产业、增加就业。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 2020年4月17日，中共中央政治局召开会议指出，要以更大的宏观政策力度对冲新冠肺炎疫情造成的影响，采取的货币政策要更加灵活适度。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 必须坚定不移地走中国特色社会主义法治道路，需要坚持法治国家、法治政府、法治体系一体建设。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 推进国家治理体系和治理能力现代化，必须发挥税收在国家治理中的基础性、支柱性、战略性作用。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 2020年3月30日，税务总局王军局长在全国税务系统全面从严治党工作会议上，做了《扛牢政治责任 补齐短板弱项--驰而不息推动税务系统全面从严治党向高质量发展》的报告。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 重大经济体制改革的进度决定着其他方面许多体制改革的进度，具有牵一发而动全身的作用。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 坚持社会主义基本经济制度，应充分发挥政府在资源配置中的决定性作用，更好发挥政府作用，全面贯彻新发展理念，坚持以供给侧结构性改革为主线，加快建设现代化经济体系。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 加强公共卫生体系建设，要加强传染病防治能力建设，完善传染病直报和预警系统。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 党的十九届四中全会通过的《决定》指出，坚定不移推进反腐败斗争，坚决查处政治问题和经济问题交织的腐败案件，坚决斩断“围猎”和甘于被“围猎”的利益链，坚决破除权钱交易的关系网。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 坚持和完善党和国家监督体系，强化对权力运行的制约和监督。完善权力配置和运行制约机制。坚持权责法定，健全分事行权、分岗设权、法定授权、分期轮岗制度，明晰权力边界，规范工作流程，强化权力制约。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 加快落实区域发展战略，要深入推进京津冀协同发展、粤港澳大湾区建设、长三角一体化发展。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "中国共产党领导是中国特色社会主义最本质的特征，是中国特色社会主义制度的最大优势，党是最高政治领导力量。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "坚持全国一盘棋，调动各方面积极性，集中力量办大事是中国特色社会主义制度的显著优势。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "73中国共产党领导的多党合作和政治协商制度是中国特色社会主义制度的重要制度。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "维护党中央权威和集中统一领导，首先要维护习近平总书记的核心地位。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "我国是工人阶级领导的、以工农联盟为基础的人民民主专政的社会主义国家，国家的一切权力属于党。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "2019年10月28日至31日，中国共产党第十九届中央委员会第四次全体会议在北京举行。会议提出坚持和完善党和国家监督体系强化对权力运行的制约和监督。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "制度的生命力在于执行，健全权威高效的制度执行机制，加强对制度执行的监督，应坚决杜绝做选择、搞变通、打折扣的现象。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "坚定不移走中国特色解决民族问题的正确道路，坚持各民族一律平等，坚持各民族共同团结奋斗、共同繁荣发展，保证民族自治地方依法行使自治权，保障少数民族合法权益巩固和发展平等团结互助和谐的社会主义民族关系。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "依法治国首先要坚持依宪治国，依法执政首先要坚持依宪执政。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "全面推进依法治国，需要坚持依法立法、依法执法、依法司法共同推进。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "81必须坚定不移地走中国特色社会主义法治道路，需要坚持法治国家、法治政府、法治体系一体建设。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "党的十九届四中全会明确提出：“深入推进简政放权、放管结合、优化服务，深化行政审批制度改革，改善营商环境，激发政府活力。” （ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "重大经济体制改革的进度决定着其他方面许多体制改革的进度，具有牵一发而动全身的作用。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "要实现各种所有制经济的权利平等、机会平等、发展平等。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "根据党的十九届四中全会精神，我们要坚决同一切影响党的先进性、弱化党的纯洁性的问题作斗争，大力纠治形式主义、官僚主义，不断增强党的创造力、凝聚力、战斗力，确保党始终成为中国特色社会主义事业的坚强领导核心。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "加快建立现代财政制度是完善和发展中国特色社会主义制度、推进国家治理体系和治理能力现代化的题中应有之义。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "推进国家治理体系和治理能力现代化，必须发挥税收在国家治理中的基础性、支柱性、战略性作用。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "《中国共产党第十九届中央委员会第四次全体会议公报》提出，适当加强中央在知识产权保护、养老保险、跨区域生态环境保护等方面事权，减少并规范中央和地方共同事权。赋予地方更多自主权，支持地方创造性开展工作。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "中国共产党第十九届中央委员会第四次全体会议支出：要增进人民福祉、促进人的全面发展是我们党立党为公、执政为民的本质要求。创新公共服务提供方式，鼓励支持社会力量兴办公益事业，满足人民多层次多样化需求，使改革发展成果更多更公平惠及全体人民。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "当今世界正经历百年未有之大变局，我国正处于实现中华民族伟大复兴关键时期。顺应时代潮流，适应我国社会主要矛盾变化，统揽伟大斗争、伟大工程、伟大事业、伟大梦想，不断满足人民对美好生活新期待，战胜前进道路上的各种风险挑战，必须在坚持和完善中国特色社会主义制度、推进国家治理体系和治理能力现代化上下更大功夫。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "坚持全国武装力量由军委主席统一领导和指挥，完善贯彻军委主席负责制的体制机制，严格落实军委主席负责制各项制度规定。 （ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "坚持社会主义基本经济制度，应充分发挥政府在资源配置中的决定性作用，更好发挥政府作用，全面贯彻新发展理念，坚持以供给侧结构性改革为主线，加快建设现代化经济体系。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "坚持按劳分配为主体、多种分配方式并存，应坚持多劳多得，着重保护劳动所得，增加劳动者特别是一线劳动者劳动报酬，提高劳资本要素在初次分配中的比重。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "“一国两制”是党领导人民实现祖国和平统一的一项重要制度，是中国人民的一个伟大创举。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "95坚持奉行防御性的国防政策，永远不称霸，永远不搞扩张，永远做维护世界和平的坚定力量。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "坚持和完善党和国家监督体系，强化对权力运行的制约和监督。完善权力配置和运行制约机制。坚持权责法定，健全分事行权、分岗设权、法定授权、分期轮岗制度，明晰权力边界，规范工作流程，强化权力制约。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "完善坚持正确导向的舆论引导工作机制，应坚持党管媒体原则，建立以新媒体建设为根本、先进技术为支撑、创新管理为保障的全媒体传播体系。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "2020年3月30日，税务总局王军局长在全国税务系统全面从严治党工作会议上，做了《扛牢政治责任 补齐短板弱项--驰而不息推动税务系统全面从严治党向高质量发展》的报告。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "推动税务系统全面从严治党，要坚持不懈压牢压实各级税务局党委和班子成员特别是“纪检组长”管党治党责任。（ ）", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "2020年3月30日，税务总局王军局长在全国税务系统全面从严治党工作会议上指出， 各级税务局党委和党员干部，更要认真学习贯彻习近平总书记重要指示精神，树牢税务机关首先是政治机关的意识，切实做到旗帜鲜明讲政治。（ ）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 根据《中华人民共和国民法典》，禁止高利放贷，借款的利率不得违反国家有关规定。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 根据《中华人民共和国民法典》，民事主体从事民事活动，应当遵循诚信原则，合理确定各方的权利和义务。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 根据《中华人民共和国民法典》，处理民事纠纷，应当依照法律；法律没有规定的，可以适用习惯，但不得违背公序良俗。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 中国特色社会主义法治建设的根本目的是保障人民权益。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "判断题 根据《中华人民共和国民法典》，民事主体在民事活动中的法律地位一律平等。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "5. 总局党建工作领导小组成员单位包括办公厅、人事司、党建工作局、机关党委、教育中心、宣传中心、督察内审司、稽查局。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "制定《中国共产党党和国家基层组织工作条例》是党的十九大之后的首创", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "机关基层党组织领导本单位业务工作", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "机关党的代表大会实行任期制", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "党的机关工作委员会统一领导所属机关党的工作，指导督促各单位党组（党委）落实机关党建主体责任.", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "十九大指出，中国共产党人的初心和使命，就是为人民谋幸福，为中华谋复兴。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "形式主义的要害是务虚不务实", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "官僚主义的要害是做官不做事。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "“客里空”是苏联1942年出版的剧本《前线》中的一个角色--前线特派记者。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "企业可以延缓支付劳动报酬，但是不得制定损害劳动者安全健康的考核指标﹙  ﹚。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "构建新发展格局，实行高水平对外开放，必须具备强大的国外经济循环体系和稳固的基本盘﹙  ﹚。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "要增强政治意识，善于从讲政治的高度思考和推进经济社会发展工作，提高专业化水平，努力成为构建新发展格局的行家里手 ﹙  ﹚。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "立足国际大循环，发挥比较优势，协同推进强大国内市场和贸易强国建设，以国际大循环吸引全球资源要素，充分利用国内国际两个市场两种资源，积极促进内需和外需、进口和出口、引进外资和对外投资协调发展，促进国际收支基本平衡﹙  ﹚。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "《中华人民共和国印花税法（草案）》总结印花税暂行条例多年实践做法，总体保持现行税制不变，并将证券交易印花税纳入法律规范﹙  ﹚。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "今年为了应对前所未有的困难，我们出台的宏观经济政策，突出是助力经济发展和拉动市场内需，着力推动宏观调控与微观需求紧密结合﹙  ﹚。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "完善现代税收制度，健全地方税、直接税体系，优化税制结构，适当提高直接税比重，深化税收 征管制度改革﹙  ﹚。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "今年新增财政赤字1万亿元、发行抗疫特别国债1万亿元，同时实施了规模超过2.5万亿元的减税降费政策，其中又以减税为主﹙  ﹚。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "构建金融有效支持实体经济的体制机制，提升金融科技水平，增强金融普惠性﹙ ﹚。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "向上级机关请示、汇报工作或对重要问题提出建议时可以用“请示”“报告”或“意见”﹙ ﹚。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "税务总局2020年版绩效指标中，共对司局、省局、驻各地特派办“三类对象”进行考评﹙  ﹚。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "“税收改革发展”类指标重点突出贯彻落实党的十九届三中全会通过的《中共中央关于深化党和国家机构改革的决定》， 围绕落实落细税收主题主业主线工作，加强对组织税费收入、支持疫情防控和经济社会发展、拓展减税降费成效，以及各税种管理、社保非税管理、纳税服务、税收征管、大企业管理、稽查管理和信息化建设方面的考评﹙  ﹚。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "税务总局2020年版绩效指标在考评机制上加强了督考衔接，将考评司局个性指标任务部分纳入督办，机关督办部门按月督办并按照考评标准实施考评，绩效办进行复核﹙  ﹚。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "税务绩效管理坚持科学合理，客观公正的原则，建立健全定性为主的工作目标，形成科学完备的绩效管理制度体系﹙  ﹚。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "“建立健全定性为主的工作目标”应改为“建立健全可量化、能定责、可追责的工作目标”。正确的说法是：税务绩效管理坚持科学合理，客观公正的原则， 建立健全可量化、能定责、可追责的工作目标，形成科学完备的绩效管理制度体系。科学决策是做好工作的基本功﹙  ﹚。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "培训住宿不得安排高档套房，可以额外配发洗漱用品﹙  ﹚。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "公务员晋升领导职务，应当具备拟任职务所要求的政治素质、工作能力、文化程度和任职经历等方面的条件和资格。公务员领导职务绝对不能越级晋升﹙  ﹚。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "纳税人、扣缴义务人办理延期申报，应当由省级税务机关批准﹙  ﹚。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "经省级税务机关批准，纳税人延期缴纳税款的，在批准延期内也应当加收滞纳金﹙  ﹚。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "调取纳税人、扣缴义务人当年的账簿、记账凭证、报表和其他有关资料的，应当经所属设区的市、自治州以上税务局局长批准，并在3个月内退还﹙  ﹚。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "2019年税务总局制发了《自助办税终端管理办法》和《自助办税终端业务规范》，规范自助办税终端的管理和使用﹙ ﹚。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "“非接触式”办税缴费服务仅限于疫情防控期间﹙ ﹚。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "为扩大优惠政策的宣传面，税务总局在12366纳税服务平台开辟了“疫情防控税收优惠政策措施”、“小微企业和个体工商户的服务”和“减税降费”专栏﹙  ﹚。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "为方便纳税人、缴费人全面了解各项税费优惠政策，税务部门全面梳理了各项支持疫情防控和复工复产的税费优惠政策及相关的征管服务措施，对各项政策的适用主体、优惠内容、操作流程进行“全景式” 的介绍﹙ ﹚。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "纳税人需求征集类型包括全面征集、日常征集和定向征集﹙  ﹚。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "纳税人满意度全面调查，主要考评各地税务部门纳税服务工作情况﹙  ﹚。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "近年来中国税务部门大力推进纳税便利化改革，压缩纳税时间，世界银行《营商环境报告》显示，我国近三年纳税时间压缩121小时，压缩比例46.7%﹙ ﹚。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "非经常性指标缺失是指在评价年度内，税务管理系统中没有纳税评估、大企业税务审计、反避税调查或税务稽查出具的决定（结论）文书的记录﹙ ﹚。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "纳税信用级别为A、B、C的—般纳税人可以不进行增值税发票认证，D级纳税人仍需扫描认证﹙  ﹚。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "2000年度”便民办税春风行动”着眼于落实落细习近平总书记重要讲话精神和党中央、国务院决策部署，从“支持疫情防控帮扶企业纾困解难、推动企业复工复产、服务纳税人缴费人办税缴费、优化税收营商环境” 等4个方面推出了24项76条措施﹙  ﹚。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "今年的”便民办税春风行动”着眼于落实落细习近平总书记重要讲话精神和党中央、国务院决策部署，从“支持疫情防控帮扶企业纾困解难、推动企业复工复产、服务国家发展战略、优化税收营商环境” 等4 个方面推出了24项76条措施。故本题错误。便民办税春风行动的“春风”并非自然之风，它是通过税务部门提供优质便捷高效的办税缴费服务，让纳税人、缴费人有如沐春风之感﹙ ﹚。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "关于支持个体工商户复工复业增值税政策、关于支持新型冠状病毒感染的肺炎疫情防控有关个人所得税政策和有关捐赠税收政策，执行期限均延长至2021年12月31日﹙ ﹚。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "增值税—般纳税人提供公共交通运输服务可以选择适用简易计税方法计税﹙ ﹚。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "政府信息，是指党政机关在履行职责过程中制作或者获取的，以—定形式记录、保存的信息﹙  ﹚。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "税务总局2020年版绩效指标中， 共对司局、省局、驻各地特派办“三类对象”进行考评﹙  ﹚。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "“税收改革发展”类指标重点突出贯彻落实党的十九届三中全会通过的《中共中央关于深化党和国家机构改革的决定》，围绕落实落细税收主题主业主线工作，加强对组织税费收入、支持疫情防控和经济社会发展、拓展减税降费成效，以及各税种管理、社保非税管理、纳税服务、税收征管、大企业管理、稽查管理和信息化建设方面的考评﹙  ﹚。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "税务总局2020年版绩效指标在考评机制上加强了督考衔接，将考评司局个性指标任务部分纳入督办，机关督办部门按月督办并按照考评标准实施考评，绩效办进行复核﹙ ﹚。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "税务绩效管理坚持科学合理，客观公正的原则，建立健全定性为主的工作目标，形成科学完备的绩效管理制度体系﹙  ﹚。", "F", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "税务总局党委在2019年落实减税降费过程中形成的“短平决优”“九个—“工作法的具体内容是：— 面旗引领、—盘棋统筹、—张表推进、—竿子到底、 一揽子服务、一个口答疑、—把尺核算、—体式督导、—股绳聚力。﹙ ﹚。", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "“十四五”《建议》提出，提高国防和军队现代化质量效益，要打造高水平战略威慑和联合作战体系，加强军事力量联合训练、联合保障、联合运用。（）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "推进两岸关系和平发展和祖国统一，应坚持一个中国原则和“九二共识”，以两岸同胞福祉为依归，推动两岸关系和平发展、融合发展，加强两岸产业合作，打造两岸共同市场，壮大中华民族经济，共同弘扬中华文化。（）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "实施乡村建设行动，应该强化县城综合服务能力，把乡镇建成服务农民的区域中心。（实施乡村建设行动，应该强化县城综合服务能力，把乡镇建成服务农民的区域中心。（）", "T", 1,1,"税务");
insert into judge_question (subject,question,answer,score,level,section) value("所有题目", "立足国际大循环，发挥比较优势，协同推进强大国内市场和贸易强国建设，以国际大循环吸引全球资源要素，充分利用国内国际两个市场两种资源，积极促进内需和外需、进口和出口、引进外资和对外投资协调发展，促进国际收支基本平衡。", "F", 1,1,"税务");
